config/routes.rb
Rails.application.routes.draw do
  root 'reservation#index'
  resources :reservation

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  validates :time, presence: true
  validates :name, presence: true
  validates :seats, presence: true
  validates :date, presence: true, not_in_past: true 
  validates_numericality_of :seats, greater_than: 0
  before_validation :tables_available?, {message: "No Tables Available"}
  after_save :create_tables
  has_many :tables, dependent: :destroy

  def time_display
    if self.time == 0
      "12:00am"
    elsif self.time == 12
      "12:00pm"
    elsif self.time/12 >0
      "#{self.time-12}:00pm"
    else 
      "#{self.time}:00am"
    end
  end 


  def tables_available? 
    tables_available >= tables_needed
  end
  def tables_available 
    TableCount.four_seater - Table.where(time: self.time, date: self.date).count
  end
  def tables_needed
    seats = self.seats || 1
    return seats/4 if seats%4 == 0
    return seats/4 + 1
  end
  def tables_used 
    TableCount.four_seater - Table.where(time: self.time, date: self.date).count
  end
  def create_tables
    number_of_tables = tables_needed  
    number_of_tables.times { |x| Table.create(time: self.time, date: self.date, size: 4, reservation_id: self.id) }
  end

end

app/models/table.rb
class Table < ActiveRecord::Base
  belongs_to :reservation
  validates :size, presence: true 
  validates :time, presence: true
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservation_controller.rb
class ReservationController < ApplicationController
  def index
    @reservations = Reservation.all
  end
  def new
    @seats = (1..20).to_a
    @reservation = Reservation.new
  end
  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:success] = ["Your Table has been reserved" ]
      redirect_to root_path
    elsif !@reservation.tables_available?
      flash[:warning] = ["No tables available, only #{@reservation.tables_available}, four seater tables left"] unless @reservation.tables_available?
      redirect_to new_reservation_path
    else 
      flash[:warning] = @reservation.errors.full_messages
      redirect_to new_reservation_path
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservation_index_path
  end

  private 
  def reservation_params 
    params[:reservation][:time] = params[:date][:hour]
    params.require(:reservation).permit(:time, :name, :seats, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservation System</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%=action_name %>">
<nav class="nav-bar">
  <div class="container-fluid">
    <h1>Reservation</h1>
  </div>
</nav>
<% if flash %> 
<div class="cointainer-fluid">
  <% flash.each do |key, value| %> 
    <% value.each do |v| %>
      <div class="alert alert-<%= key %>">
        <small><%=v%></small>
      </div>
    <% end %> 
  <% end %> 
</div>
<% end %> 
<%= yield %>
<footer class="footer">
  <div class="container-fluid">
    <p class="text-muted">Web Application by Robert Dalin</p>
  </div>
</footer>
</body>
</html>

app/views/reservation/index.html.erb
<div class="container-fluid">
  <h4>This Restaurant has <%=TableCount.four_seater%> four seater tables and can seat up to <%=TableCount.four_seater * 4 %> people</h4>
  <h4><a href="/reservation/new" class="navbar-left"><small>New Reservation?</small></a></h4>
</div>
<div class="container-fluid">

  <% if @reservations.count > 0 %> 
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Start Time</th>
      <th>Date</th>
      <th>No. of Seats</th>
      <th>No. of Tables</th>
      <th>Delete</th>
    </tr>
    <% @reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.name %></td>
      <td><%= reservation.time_display %></td>
      <td><%= "#{reservation.date.strftime("%B %d, %Y")} " if reservation.date %></td>
      <td><%= reservation.seats %></td>
      <td><%= reservation.tables_needed %></td>
      <td><%= link_to "Cancel Reservation", reservation_path(reservation), method: :delete, data: {confirm: "Are you sure you want to cancel this reservation?"}%></td>
    </tr>
    <% end %> 
  </table>
  <% else %> 
  <p>No Reservations at this time</p>
  <% end %> 

</div>

app/views/reservation/new.html.erb
<div class="container-fluid">
  <h3><a href="/"><small>Home</small></a></h3>
  <h3>Enter in a new reservation</h3>
  <%= form_for @reservation, url: {action: "create"} do |f| %>
    <div class="form-group">
      <label>Name: </label>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <label>Seats: </label>
      <%= f.select(:seats, options_for_select(@seats))%>
    </div>
    <div class="form-group">
      <label>Date: </label>
      <%= f.text_field :date, id: "date" %> 
    </div>
    <div class="form-group">
      <label>Time: </label>
        <%= select_hour Time.now+1.hour, start_hour: 0, end_hour: 23, ampm: true %> 
      </div>
     <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
       <i class="icon-ok icon-white"></i> Reserve
     <% end %>
  <% end %>
</div>